# Generated by Django 5.0.6 on 2024-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostel',
            field=models.CharField(blank=True, choices=[('1', 'Old boys Hostel'), ('2', 'New boys Hostel'), ('3', 'Old Girls Hostel'), ('4', 'New Girls Hostel')], max_length=10, null=True),
        ),
    ]
