# Generated by Django 5.0.6 on 2024-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
