# Generated by Django 5.0.6 on 2024-07-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_complaint_options_complaint_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('date_added',), 'verbose_name_plural': 'complaints'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.categorycomplaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='hostel',
            field=models.CharField(blank=True, choices=[('1', 'old boys hostel'), ('2', 'new boys hostel'), ('3', 'old girls hostel'), ('4', 'new girls hostel 1'), ('5', 'new girls hostel 2')], max_length=10, null=True),
        ),
    ]
