# Generated by Django 5.0.3 on 2024-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycomplaint',
            name='cat_desc',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
