# Generated by Django 5.0.3 on 2024-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categorycomplaint_cat_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='hostel',
            field=models.CharField(blank=True, choices=[('old boys hostel', '1'), ('new boys hostel', '2'), ('old girls hostel', '3'), ('new girls hostel 1', '4'), ('new girls hostel 2', '5')], max_length=50, null=True),
        ),
    ]
