# Generated by Django 5.0.3 on 2024-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_complaint_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='hostel',
            field=models.CharField(blank=True, choices=[('old boys hostel', 'OBH'), ('new boys hostel', 'NBH'), ('old girls hostel', 'OGH'), ('new girls hostel 1', 'NGH1'), ('new girls hostel 2', 'NGH2')], max_length=50, null=True),
        ),
    ]
