# Generated by Django 5.0.3 on 2024-07-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_complaint_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'complaints'},
        ),
    ]
