# Generated by Django 5.0.3 on 2024-07-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_complaint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycomplaint',
            name='cat_slug',
            field=models.SlugField(blank=django.db.models.deletion.SET_NULL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(blank=django.db.models.deletion.SET_NULL),
        ),
    ]
