# Generated by Django 5.0.3 on 2024-07-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categorycomplaint_cat_slug_complaint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='block',
            field=models.CharField(blank=True, choices=[('enoch', 'Block A'), ('Daniel', 'Block B'), ('moses', 'Block C')], max_length=50, null=True),
        ),
    ]
