# Generated by Django 5.0.3 on 2024-07-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_categorycomplaint_cat_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycomplaint',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
