# Generated by Django 5.0.3 on 2024-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_categorycomplaint_slug_alter_complaint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
