# Generated by Django 5.0.3 on 2024-08-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_complaint_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='slug',
        ),
    ]
